In [ ]:
# Data Structures in R

#
# In R, based on data type the data structure can be divided into 2 categories:
#   1. Single data type (Vector, Matrix, Array)
#   2. Multiple data type (DataFrame, List)


In [ ]:
# Vector

x1 <- c(5,3,76,33,77,98,22)
is.vector(x1)
is.data.frame(x1)

[1] TRUE

[1] FALSE

In [ ]:
# Random number generator

set.seed(769)  # set.seed() is actually used for setting a static value so that others get the same random sample value using the same seed. if we don't use set.seed() then other's will get different different values every time.
x2 <- sample(1:100, 10)
x2
summary(x2)

x3 <- sample(1:10, 8, replace = TRUE)  # replace = True means same number can repeat multiple times
table(x3)  # used for count the numbers


x4 <- runif(5)  # used to generate random numbers between 0 and 1.
x4

prob_weights = c(4, 6, 2, 6, 1)
fruits <- sample(c("Apple", "Banana", "Mango", "Litchi", "Orange"), 3, replace = TRUE, prob = prob_weights)
fruits




[1] 80 30 94 71 85 48 81 39 96 43

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  30.00   44.25   75.50   66.70   84.00   96.00 

x3
 1  2  4  8  9 10 
 1  1  2  1  2  1 

[1] 0.1174993 0.3827622 0.9027812 0.7233591 0.6244725

[1] "Banana" "Litchi" "Litchi"

In [ ]:
# Sequence Generator
x5 <- 1:15
x5
x6 <- 10:1
x6

x7 = seq(from = 1, to = 10, by = 3)  # 'by' defines the gap between numbers
x7

x8 = seq(from = 1, to = 15, length.out = 5) # 'length.out' defines a definite gap between numbers. we don't define it. it will be defined automatically
x8

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

[1] 10  9  8  7  6  5  4  3  2  1

[1]  1  4  7 10

[1]  1.0  4.5  8.0 11.5 15.0

In [ ]:
# Selection
x1 > 50
x1[c(FALSE, FALSE,TRUE, FALSE, TRUE, TRUE, TRUE)]
x1[c(2, 4, 1)]
x1[x1>50]
x1[x1> 30 & x1<50]
which(x1>30 & x1<50)
x1[which(x1>30 & x1<50)]

[1] FALSE FALSE  TRUE FALSE  TRUE  TRUE FALSE

[1] 76 77 98 22

[1]  3 33  5

[1] 76 77 98

[1] 33

[1] 4

[1] 33

In [ ]:
# Replace

# Don't replace original
replace(x1, x1>30, 50)
x1 <- replace(x1, which(x1>30), NA)
x1

avg = mean(x1, na.rm = TRUE)
avg
# Replace original
x1[is.na(x1)] <- 10
x1
x9 <- c(5,3,76,33,77,98,22)
x9[x9 > 70] <- 58
x9

[1]  5  3 10 10 10 10 22

[1]  5  3 10 10 10 10 22

[1] 10

[1]  5  3 10 10 10 10 22

[1]  5  3 58 33 58 58 22

In [7]:
# Matrix

mat1 <- matrix(c(3,2,4,1,8,4), ncol=3, nrow=2, byrow=TRUE)
print(mat1)
is.matrix(mat1)

is.matrix(c(0,2,3))

print(mat1[,])
print(mat1[2,])
print(mat1[,1])
print(mat1[2,2])
mat1[2,2] <- 0
print(mat1)

mat2 <- matrix(c(0,1,2), ncol = 1)
print(mat2)

     [,1] [,2] [,3]
[1,]    3    2    4
[2,]    1    8    4


[1] TRUE

[1] FALSE

     [,1] [,2] [,3]
[1,]    3    2    4
[2,]    1    8    4
[1] 1 8 4
[1] 3 1
[1] 8
     [,1] [,2] [,3]
[1,]    3    2    4
[2,]    1    0    4
     [,1]
[1,]    0
[2,]    1
[3,]    2


In [15]:
mat4 <- matrix(c(1,2,3,4,5,6), 2, 3, TRUE)
mat5 <- matrix(c(4,5,6,7,8,9), 3, 2, TRUE)
mat6 <- matrix(c(1,2,3),3, byrow = TRUE)
dim(mat5)
dim(mat6)
# Element wise multiplication(Hadamard Multiplicaiton)
mat7 <- matrix(c(2,2,3,4),2)
mat8 <- matrix(c(4,4,5,5),2)
print(mat7 * mat8)

# Matrix Multiplication
print(mat4 %*% mat5)

# Kronecker Product
print(mat4 %x% mat6)


[1] 3 2

[1] 3 1

     [,1] [,2]
[1,]    8   15
[2,]    8   20
     [,1] [,2]
[1,]   40   46
[2,]   94  109
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    2    4    6
[3,]    3    6    9
[4,]    4    5    6
[5,]    8   10   12
[6,]   12   15   18


In [17]:
# Array

arr1 <- array(c(1:15), c(2,3,3))  # second c() funciton cointain c(row,column,layer)
print(arr1)


, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15    2
[2,]   14    1    3



In [24]:
# Data Frame

df1 = data.frame(
  ID = c(1,2,3),
  Age = c(24,23,26),
  Gender = c("M", "M", "F"),
  stringsAsFactors = TRUE
)
df1
summary(df1)



ID,Age,Gender
<dbl>,<dbl>,<fct>
1,24,M
2,23,M
3,26,F


       ID           Age        Gender
 Min.   :1.0   Min.   :23.00   F:1   
 1st Qu.:1.5   1st Qu.:23.50   M:2   
 Median :2.0   Median :24.00         
 Mean   :2.0   Mean   :24.33         
 3rd Qu.:2.5   3rd Qu.:25.00         
 Max.   :3.0   Max.   :26.00         